name: Continuous Integration
on:
  push:
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          go install go.nc0.fr/crocc@latest
      - name: Make
        run: |
          make clean
          make
      - name: Deploy site
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 8279a0db87c255a58a89ca7fd11612ab
          projectName: nc0-fr
          directory: dst
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
